name: CMake Build Matrix

on:
  push:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows",
            os: windows-latest,
            artifact: "windows",
            build_type: "Release",
            cc: "clang",
            cxx: 'clang++',
            archiver: "zip",
            generators: "Ninja"
          }

    steps:
      - uses: actions/checkout@v2

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Install choco on windows
        if: startsWith(matrix.config.name, 'Windows')
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        
      - name: Install cmake on windows
        if: startsWith(matrix.config.name, 'Windows')
        shell: pwsh
        run: |
          choco install cmake