name: Windows

on:
  push:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows",
            os: windows-latest,
            artifact: "windows",
            build_type: "Release",
            cc: "clang",
            cxx: 'clang++',
            archiver: "zip",
            generators: "Ninja"
          }

    steps:
      - uses: actions/checkout@v2

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Install choco on windows
        if: startsWith(matrix.config.name, 'Windows')
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        
      - name: Install Dependencies on windows
        if: startsWith(matrix.config.name, 'Windows')
        shell: pwsh
        run: |
          choco install git zip unzip vim curl wget msys2
          pacman -S mingw-w64-x86_64-gcc
          pacman -S base-devel
          pacman -S binutils
          pacman -S python
          pacman -S git
          pacman -S mingw-w64-x86_64-toolchain
          pacman -S mingw-w64-x86_64-lapack
          pacman -S mingw-w64-x86_64-msmpi
          pacman -S mingw-w64-x86_64-libxml2
          pacman -S mingw-w64-x86_64-cmake
          pacman -S mingw-w64-x86_64-doxygen
          pacman -S mingw-w64-x86_64-graphviz
          pacman -S mingw-w64-x86_64-rapidjson
          pacman -S mingw-w64-x86_64-petsc
          pacman -S mingw-w64-x86_64-petsc-build
